services:
  db:
    image: postgres:13.3
    container_name: employee_directory_database
    environment:
      POSTGRES_DB: employee_directory_database
      POSTGRES_USER: root
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_PASSWORD: root
    command: [
      postgres,
      -c, log_statement=all,
      -c, log_connections=on,
      -c, "log_line_prefix=%m [%p]: [%l-1] user=%u,client=%h,db=%d,app=%a "
    ]
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

